# Generated by Django 4.1.2 on 2022-11-01 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('avatar', models.ImageField(null=True, upload_to='profiles/')),
                ('first_name', models.CharField(max_length=225, null=True)),
                ('last_name', models.CharField(max_length=225, null=True)),
                ('references', models.CharField(max_length=225, null=True)),
                ('level_preferred', models.CharField(choices=[('Elementary', 'Elementary'), ('Middle', 'Middle'), ('High', 'High')], max_length=25, null=True)),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('SS', 'SS'), ('LA', 'LA')], max_length=25, null=True)),
                ('bio', models.TextField(null=True)),
                ('email', models.CharField(max_length=225, null=True)),
                ('joined_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(null=True, upload_to='profiles/')),
                ('first_name', models.CharField(max_length=225, null=True)),
                ('last_name', models.CharField(max_length=225, null=True)),
                ('level_preferred', models.CharField(choices=[('Elementary', 'Elementary'), ('Middle', 'Middle'), ('High', 'High')], max_length=25, null=True)),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('SS', 'SS'), ('LA', 'LA')], max_length=25, null=True)),
                ('email', models.CharField(max_length=225, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
