# Generated by Django 4.1.3 on 2022-11-05 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_is_student_alter_user_is_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(null=True, upload_to='profiles/')),
                ('location', models.CharField(max_length=225, null=True)),
                ('grade_level', models.CharField(choices=[('Elementary', 'Elementary'), ('Middle', 'Middle'), ('High', 'High')], max_length=25, null=True)),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('SS', 'SS'), ('LA', 'LA')], max_length=25, null=True)),
                ('bio', models.TextField(null=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='student',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(null=True, upload_to='profiles/')),
                ('level_preferred', models.CharField(choices=[('Elementary', 'Elementary'), ('Middle', 'Middle'), ('High', 'High')], max_length=25, null=True)),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('SS', 'SS'), ('LA', 'LA')], max_length=25, null=True)),
                ('bio', models.TextField(null=True)),
                ('location', models.CharField(max_length=225, null=True)),
                ('admin_verified', models.BooleanField(default=False)),
                ('is_certified', models.BooleanField(default=False)),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('rating', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('trainerprofile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tutorprofile')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tutor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tutorprofile'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='tutor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tutorprofile'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
