# Generated by Django 4.1.3 on 2022-11-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentprofile_remove_tutor_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='first_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='last_name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
