# Generated by Django 4.1.3 on 2022-11-06 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studentprofile_first_name_studentprofile_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='trainerprofile',
            new_name='tutorprofile',
        ),
    ]
