# Generated by Django 4.1.3 on 2022-11-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_studentprofile_user_alter_tutorprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='email',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
