# Generated by Django 4.1.3 on 2022-11-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_studentprofile_email_tutorprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='grade_level',
            field=models.CharField(choices=[('Elementary', 'Elementary'), ('Middle School', 'Middle'), ('High School', 'High')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='subject',
            field=models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('Language Arts', 'Language Arts')], max_length=25, null=True),
        ),
    ]
