# Generated by Django 4.1.3 on 2022-11-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_studentprofile_grade_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='grade_level',
            field=models.CharField(choices=[('Elementary', 'Elementary'), ('Middle', 'Middle'), ('High', 'High')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='subject',
            field=models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('SS', 'SS'), ('LA', 'LA')], max_length=25, null=True),
        ),
    ]
