# Generated by Django 4.1.3 on 2022-11-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_studentprofile_grade_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='first_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='last_name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
