# Generated by Django 4.1.3 on 2022-11-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_review_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='student',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tutorprofile'),
        ),
    ]
