# Generated by Django 4.1.3 on 2022-11-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_lesson_day_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='progress',
            field=models.CharField(choices=[('Completed', 'Completed'), ('in_progress', 'in_progress'), ('not_started', 'not_started')], max_length=25, null=True),
        ),
    ]
