# Generated by Django 4.1.3 on 2022-11-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_lesson_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
