# Generated by Django 4.1.3 on 2022-11-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_lesson_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day_assigned',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='progress',
            field=models.CharField(choices=[('Completed', 'Completed'), ('in_progress', 'in_progress'), ('not_started', 'not_started')], default='not_started', max_length=25),
        ),
    ]
