# Generated by Django 4.1.3 on 2022-11-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_lesson_day_assigned_alter_lesson_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='avatar',
            field=models.ImageField(max_length=500, null=True, upload_to='profiles/'),
        ),
    ]
