# Generated by Django 4.1.3 on 2022-11-23 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='studentprofile',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='tutorprofile',
            new_name='tutor',
        ),
    ]
